name = "alicesaidhi/conch_ui"
version = "0.3.0-rc.2"
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
vide = { wally = "wally#centau/vide", version = "^0.3.1" }
language = { workspace = "alicesaidhi/conch_language", version = "^", target = "roblox" }
conch = { workspace = "alicesaidhi/conch", version = "^" }
